# Generated by Django 2.0.3 on 2018-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=250)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('following', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('total', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
