# Generated by Django 2.0.3 on 2018-04-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
