# Generated by Django 2.0.3 on 2018-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0002_auto_20180427_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ranking',
        ),
    ]
