# Generated by Django 2.0.3 on 2018-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderBoard', '0003_remove_user_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('following', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('total', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
